import { createPagesFunctionHandler } from "@react-router/cloudflare";
import type { ServerBuild } from "react-router";

// @ts-ignore - the server build file is generated by `react-router build`
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({
    build: build as ServerBuild,
});
