[project]
name = "syllabus-scraping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "playwright>=1.49.1",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
