name: "scraping"

on:
  workflow_dispatch:
    inputs:
      year:
        description: "Year"
        required: true
        type: number

jobs:
  scraping:
    name: Scraping
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: ./scraping

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set year
        id: set-year
        run: echo "YEAR=${{ github.event.inputs.year }}" >> $GITHUB_ENV

      - name: Run
        run: YEAR=${{ env.YEAR }} docker compose up --build

      - name: Create Release and Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: syllabus-${{ env.YEAR }}
          SYLLABUS_JA: scraping/data/${{ env.YEAR }}-ja.json
          SYLLABUS_EN: scraping/data/${{ env.YEAR }}-en.json
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.SYLLABUS_JA }}
            ${{ env.SYLLABUS_EN }}
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: scraping/data

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: scraping

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
